### ISSUE TITLE
Error: Can't open <file> for removed sources

### ISSUE THREAD

**Issue by bubenshchykov** [ebdrup/mocha-jshint#11]
Removed files should be ignored from any jshint run

Example:
- I deleted ErrorEmailDecorator.spec.js
- I run jshint and get error log. Expected - removed file is never mentioned again

```
jshint,
[21:54:40] service-router is started
ERROR: Can't open client/static/src/shared/utils/decorators/EmailErrorDecorator.js
ERROR: Can't open client/tests/jasmine.unittests/shared/utils/EmailErrorDecorator.spec.js
    ✓ should pass for working directory (2034ms)
```

**Comment by ebdrup** [comment]
this was fixed in v2.2.1 https://github.com/ebdrup/mocha-jshint/commit/17f309c358563a5dfd0d771f000260630daaf67f
