### ISSUE TITLE
How to change reporter? mocha.opts --reporter doesn't seem to be working

### ISSUE THREAD

**Issue by JohnKimDev** [ebdrup/mocha-jshint#21]
I tried 
--reporter spec 
and other possible reporter options but doesn't see to make difference. Also It will be nice if we can passed the customized reporter code as an option field to overwrite the default.

Thanks

**Comment by eagleeye** [comment]
@JohnKimDev reporter option works for me, including jshint test. I tried default reporter and 2 others.
```
✔ ~/prj/debitoor-app [delivery-note-form-2|⚑ 4] 
18:30 $ mocha --grep jshint


  jshint
    ✓ should pass for working directory (758ms)


  1 passing (2s)

✔ ~/prj/debitoor-app [delivery-note-form-2|⚑ 4] 
18:30 $ mocha --grep jshint --reporter dot


  ․

  1 passing (1s)

✔ ~/prj/debitoor-app [delivery-note-form-2|⚑ 4] 
18:30 $ mocha --grep jshint --reporter nyan
 1   -__,------,
 0   -__|  /\_/\ 
 0   -_~|_( ^ .^) 
     -_ ""  "" 

  1 passing (1s)

```

**Comment by eagleeye** [comment]
spec reporter is default reporter, so that's why you don't see difference
